name: llama2c
version: 0.0.1
description: >-
  Running llama2.c with Dart/Flutter

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0